# database.py
# Handles all database operations for PyHIDS
# SQLite is built into Python - no installation needed

import sqlite3
import os
from datetime import datetime

# Path to our database file - will be created automatically
DB_PATH = os.path.join(os.path.dirname(__file__), 'hids.db')


def get_connection():
    """
    Opens and returns a connection to the SQLite database.
    We call this every time we need to talk to the database.
    """
    conn = sqlite3.connect(DB_PATH)
    # This makes rows behave like dictionaries so we can do row['severity']
    # instead of row[2] - much easier to work with
    conn.row_factory = sqlite3.Row
    return conn


def initialize_database():
    """
    Creates all the tables we need if they don't already exist.
    Safe to call multiple times - won't overwrite existing data.
    """
    conn = get_connection()
    cursor = conn.cursor()

    # Alerts table - stores every alert generated by any module
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS alerts (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp   TEXT NOT NULL,
            severity    TEXT NOT NULL,
            module      TEXT NOT NULL,
            title       TEXT NOT NULL,
            description TEXT NOT NULL,
            host        TEXT NOT NULL DEFAULT 'localhost',
            resolved    INTEGER NOT NULL DEFAULT 0
        )
    ''')

    # FIM table - stores file integrity events
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS fim_events (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp   TEXT NOT NULL,
            filepath    TEXT NOT NULL,
            event_type  TEXT NOT NULL,
            old_hash    TEXT,
            new_hash    TEXT,
            host        TEXT NOT NULL DEFAULT 'localhost'
        )
    ''')

    # Log events table - stores raw suspicious log lines
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS log_events (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp   TEXT NOT NULL,
            source_file TEXT NOT NULL,
            raw_line    TEXT NOT NULL,
            pattern     TEXT NOT NULL,
            host        TEXT NOT NULL DEFAULT 'localhost'
        )
    ''')
    # Baselines table - stores the known-good SHA-256 hash of every watched file
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS baselines (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            filepath    TEXT NOT NULL UNIQUE,
            hash        TEXT NOT NULL,
            last_updated TEXT NOT NULL
        )
    ''')

    conn.commit()
    conn.close()
    print("[DB] Database initialized successfully.")


def insert_alert(severity, module, title, description, host='localhost'):
    """
    Inserts a new alert into the alerts table.

    severity  : 'CRITICAL', 'WARNING', or 'INFO'
    module    : 'FIM', 'LOG_MONITOR', 'AGENT', etc.
    title     : short description shown in dashboard
    description: full detail of what happened
    host      : which machine generated this alert
    """
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute('''
        INSERT INTO alerts (timestamp, severity, module, title, description, host)
        VALUES (?, ?, ?, ?, ?, ?)
    ''', (
        datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
        severity,
        module,
        title,
        description,
        host
    ))
    conn.commit()
    conn.close()


def insert_fim_event(filepath, event_type, old_hash=None, new_hash=None, host='localhost'):
    """
    Inserts a file integrity monitoring event.

    event_type: 'created', 'modified', or 'deleted'
    old_hash  : SHA-256 hash before change (None if file was just created)
    new_hash  : SHA-256 hash after change (None if file was deleted)
    """
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute('''
        INSERT INTO fim_events (timestamp, filepath, event_type, old_hash, new_hash, host)
        VALUES (?, ?, ?, ?, ?, ?)
    ''', (
        datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
        filepath,
        event_type,
        old_hash,
        new_hash,
        host
    ))
    conn.commit()
    conn.close()


def get_all_alerts(limit=100):
    """
    Fetches the most recent alerts from the database.
    Returns a list of dictionaries, newest first.
    """
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute('''
        SELECT * FROM alerts
        ORDER BY id DESC
        LIMIT ?
    ''', (limit,))
    rows = cursor.fetchall()
    conn.close()
    # Convert sqlite3.Row objects to plain dictionaries
    return [dict(row) for row in rows]


def get_alert_counts():
    """
    Returns a dictionary with counts for each severity level.
    Used to populate the metric cards on the dashboard.
    """
    conn = get_connection()
    cursor = conn.cursor()

    counts = {}
    for severity in ['CRITICAL', 'WARNING', 'INFO']:
        cursor.execute(
            'SELECT COUNT(*) FROM alerts WHERE severity = ?', (severity,)
        )
        counts[severity] = cursor.fetchone()[0]

    # Also get total resolved count
    cursor.execute('SELECT COUNT(*) FROM alerts WHERE resolved = 1')
    counts['RESOLVED'] = cursor.fetchone()[0]

    conn.close()
    return counts


def get_fim_events(limit=50):
    """
    Fetches recent file integrity events.
    """
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute('''
        SELECT * FROM fim_events
        ORDER BY id DESC
        LIMIT ?
    ''', (limit,))
    rows = cursor.fetchall()
    conn.close()
    return [dict(row) for row in rows]


def get_log_events(limit=50):
    """
    Fetches recent log monitor events.
    """
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute('''
        SELECT * FROM log_events
        ORDER BY id DESC
        LIMIT ?
    ''', (limit,))
    rows = cursor.fetchall()
    conn.close()
    return [dict(row) for row in rows]

def insert_log_event(source_file, raw_line, pattern, host='localhost'):
    """
    Inserts a suspicious log event into the log_events table.
    Called by the log monitor whenever a suspicious pattern is matched.
    """
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute('''
        INSERT INTO log_events (timestamp, source_file, raw_line, pattern, host)
        VALUES (?, ?, ?, ?, ?)
    ''', (
        datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
        source_file,
        raw_line,
        pattern,
        host
    ))
    conn.commit()
    conn.close()
# This block runs when you execute database.py directly
# It initializes the database and inserts one test alert
if __name__ == '__main__':
    print("[DB] Setting up database...")
    initialize_database()

    print("[DB] Inserting test alert...")
    insert_alert(
        severity='CRITICAL',
        module='TEST',
        title='Database connection test',
        description='This is a test alert to confirm the database is working correctly.',
        host='DESKTOP-WIN11'
    )

    print("[DB] Fetching all alerts...")
    alerts = get_all_alerts()
    for alert in alerts:
        print(f"  [{alert['severity']}] {alert['title']} — {alert['timestamp']}")

    counts = get_alert_counts()
    print(f"[DB] Counts: {counts}")
    print("[DB] All good!")

def get_baseline_hash(filepath):
    """
    Returns the stored baseline hash for a given filepath.
    Returns None if no baseline exists for this file yet.
    """
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute('SELECT hash FROM baselines WHERE filepath = ?', (filepath,))
    row = cursor.fetchone()
    conn.close()
    return row['hash'] if row else None


def set_baseline_hash(filepath, hash_value):
    """
    Inserts or updates the baseline hash for a given filepath.
    Uses INSERT OR REPLACE so it works for both new and existing files.
    """
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute('''
        INSERT OR REPLACE INTO baselines (filepath, hash, last_updated)
        VALUES (?, ?, ?)
    ''', (filepath, hash_value, datetime.now().strftime('%Y-%m-%d %H:%M:%S')))
    conn.commit()
    conn.close()


def get_all_baselines():
    """
    Returns all baseline entries — used to display the monitored file list.
    """
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute('SELECT * FROM baselines ORDER BY filepath')
    rows = cursor.fetchall()
    conn.close()
    return [dict(row) for row in rows]


def insert_fim_event(filepath, event_type, old_hash=None, new_hash=None, host='localhost'):
    """
    Inserts a file integrity monitoring event into fim_events table.
    Also inserts a corresponding alert so it shows on the dashboard.
    """
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute('''
        INSERT INTO fim_events (timestamp, filepath, event_type, old_hash, new_hash, host)
        VALUES (?, ?, ?, ?, ?, ?)
    ''', (
        datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
        filepath,
        event_type,
        old_hash,
        new_hash,
        host
    ))
    conn.commit()
    conn.close()